name: "Reusable Build and CodeQL Scan"

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      dotnet-version:
        required: false
        type: string
        default: "8.0.x"
      languages:
        required: false
        type: string
        default: "csharp"

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  codeql-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET (only if dotnet project)
        if: contains(inputs.languages, 'csharp')
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Build application
        if: contains(inputs.languages, 'csharp')
        run: dotnet publish ${{ inputs.project-path }} -c Release -o output

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ inputs.languages }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ inputs.languages }}"

      - name: Check for high/medium findings
        run: |
          curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/code-scanning/alerts?ref=${GITHUB_SHA}&state=open&severity=error,warning" \
            | jq > alerts.json

          if [ $(jq '. | length' alerts.json) -gt 0 ]; then
            echo "❌ Found medium/high CodeQL findings. Failing pipeline."
            cat alerts.json
            exit 1
          else
            echo "✅ No high/medium CodeQL findings found."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts (only if .NET build exists)
        if: contains(inputs.languages, 'csharp')
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-build
          path: output/
