name: "Commit Message Jira Check (Reusable)"

on:
  workflow_call:
    inputs:
      base_branch:
        description: "Base branch for comparison"
        required: true
        type: string

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate commit messages for Jira keys
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "🔍 Checking commits against Jira ticket pattern..."
          commits=$(git log ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --pretty=format:"%s")
          missing=0
          echo "$commits" | while IFS= read -r msg; do
            if ! echo "$msg" | grep -qE "([A-Z][A-Z0-9]+-[0-9]+)"; then
              echo "❌ Commit missing Jira key: $msg"
              missing=1
            fi
          done

          if [ "$missing" -eq 1 ]; then
            echo "❌ One or more commits do not include a Jira ticket. Please fix commit messages."
            exit 1
          fi

      # -----------------------------
      #  Check PR title (if exists)
      # -----------------------------
      - name: Check PR title for Jira key
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "🔍 Checking PR title for Jira key..."
          pr_title="${{ github.event.pull_request.title }}"
          if ! echo "$pr_title" | grep -qE "([A-Z][A-Z0-9]+-[0-9]+)"; then
            echo "❌ PR title missing Jira key: $pr_title"
            exit 1
          fi
          echo "✅ PR title contains Jira key: $pr_title"

      - name: Success
        run: echo "✅ All commits and PR title include Jira ticket!"