name: Manual Promotion (Blue/Green)

on:
  workflow_call:
    inputs:
      environment:
        description: "Target environment (e.g., dev, stage, prod)"
        required: true
        type: string
      main-listener-arn:
        description: "Primary ALB listener ARN"
        required: true
        type: string
      blue-target-group:
        description: "Blue Target Group ARN"
        required: true
        type: string
      green-target-group:
        description: "Green Target Group ARN"
        required: true
        type: string
      temp-listener-arn:
        description: "Temporary listener ARN (if created during deployment)"
        required: false
        type: string
      active-color:
        required: true
        description: "This is an live deployment"
        type: string
      idel-color:
        required: true
        description: "This is for new version deployment"
        type: string
      idle-tg:
        required: true
        description: "The idle target group ARN"
        type: string

jobs:
  promote:
    name: Promote Idle Deployment to Live
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment }}.yourapp.company.com

    steps:
        
      # 1️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNTID }}:role/GitHubActionsECSDeployRole
          aws-region: us-east-2
          audience: sts.amazonaws.com

      - name: Get idle color from previous Job
        run: |
          echo "ACTIVE_COLOR=${{ inputs.active-color }}"
          echo "IDLE_COLOR=${{ inputs.idel-color }}"
          echo "IDLE_TG=${{ inputs.idle-tg}}"

      # 2️⃣ Manual flip traffic
      - name: Flip Traffic to New Version
        if: ${{ inputs.idle-tg != '' }}  # Skip first deployment
        run: |
          IDLE_TG=${{ inputs.idle-tg}}
          IDLE_COLOR=${{ inputs.idel-color }}
          echo "Flipping traffic to $IDLE_COLOR..."
          aws elbv2 modify-listener \
            --listener-arn "${{ inputs.main-listener-arn }}" \
            --default-actions '[{"Type":"forward","TargetGroupArn":"'"$IDLE_TG"'"}]'

          echo "✅ Traffic successfully flipped to $IDLE_COLOR"

      # 3️⃣ Remove temporary listener if exists
      - name: Remove Temporary Listener
        if: ${{ inputs.temp-listener-arn }}
        run: |
          echo "Removing temporary listener: ${{ inputs.temp-listener-arn }}"
          aws elbv2 delete-listener --listener-arn "${{ inputs.temp-listener-arn }}"
          echo "✅ Temporary listener removed"

      # 4️⃣ Scale down old ECS service
      - name: Scale down old service
        if: ${{ inputs.idle-tg != '' }}  # Skip first deployment
        run: |
          CLUSTER_NAME="${{ vars.AWS_CLUSTER_NAME }}"
          BASE_SERVICE_NAME="${INPUT_SERVICE_NAME:-$(basename $GITHUB_REPOSITORY)}"
          BLUE_SERVICE="${BASE_SERVICE_NAME}-blue"
          GREEN_SERVICE="${BASE_SERVICE_NAME}-green"

          ACTIVE_TG="${{ inputs.active-tg }}"
          BLUE_TG="${{ inputs.blue-tg-arn }}"
          GREEN_TG="${{ inputs.green-tg-arn }}"

          if [ "$ACTIVE_TG" = "$BLUE_TG" ]; then
              ACTIVE_COLOR="blue"
              IDLE_COLOR="green"
              IDLE_TG="$GREEN_TG"
              OLD_SERVICE="$BLUE_SERVICE"
          else
              ACTIVE_COLOR="green"
              IDLE_COLOR="blue"
              IDLE_TG="$BLUE_TG"
              OLD_SERVICE="$GREEN_SERVICE"
          fi

          echo "Scaling down old ECS service ($OLD_SERVICE) with color $ACTIVE_COLOR..."

          aws ecs update-service \
            --cluster "$CLUSTER_NAME" \
            --service "$OLD_SERVICE" \
            --desired-count 0

          echo "✅ Old service scaled down to 0. Blue/Green cleanup complete."